/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as ApiR2UploadRouteImport } from './routes/api.r2-upload'
import { Route as ApiR2ListImagesRouteImport } from './routes/api.r2-list-images'
import { Route as ApiR2ImageRouteImport } from './routes/api.r2-image'
import { Route as BrandsVersaceIndexRouteImport } from './routes/brands/versace/index'
import { Route as BrandsToryBurchIndexRouteImport } from './routes/brands/tory-burch/index'
import { Route as BrandsRoughplayIndexRouteImport } from './routes/brands/roughplay/index'
import { Route as BrandsPradaIndexRouteImport } from './routes/brands/prada/index'
import { Route as BrandsPantallasIndexRouteImport } from './routes/brands/pantallas/index'
import { Route as BrandsNikeIndexRouteImport } from './routes/brands/nike/index'
import { Route as BrandsNewBalanceIndexRouteImport } from './routes/brands/new-balance/index'
import { Route as BrandsMixedEmotionsIndexRouteImport } from './routes/brands/mixed-emotions/index'
import { Route as BrandsMediasIndexRouteImport } from './routes/brands/medias/index'
import { Route as BrandsLouisVuittonIndexRouteImport } from './routes/brands/louis-vuitton/index'
import { Route as BrandsLifeHustlersIndexRouteImport } from './routes/brands/life-hustlers/index'
import { Route as BrandsJordanIndexRouteImport } from './routes/brands/jordan/index'
import { Route as BrandsJordanGorrasIndexRouteImport } from './routes/brands/jordan-gorras/index'
import { Route as BrandsHermesParisIndexRouteImport } from './routes/brands/hermes-paris/index'
import { Route as BrandsHellstarIndexRouteImport } from './routes/brands/hellstar/index'
import { Route as BrandsGucciIndexRouteImport } from './routes/brands/gucci/index'
import { Route as BrandsGodspeedIndexRouteImport } from './routes/brands/godspeed/index'
import { Route as BrandsGivenchyIndexRouteImport } from './routes/brands/givenchy/index'
import { Route as BrandsGalleryDeptIndexRouteImport } from './routes/brands/gallery-dept/index'
import { Route as BrandsFendiIndexRouteImport } from './routes/brands/fendi/index'
import { Route as BrandsEssentialsIndexRouteImport } from './routes/brands/essentials/index'
import { Route as BrandsDolceGabanaIndexRouteImport } from './routes/brands/dolce-gabana/index'
import { Route as BrandsDiorIndexRouteImport } from './routes/brands/dior/index'
import { Route as BrandsDandihatsIndexRouteImport } from './routes/brands/dandihats/index'
import { Route as BrandsCorreasIndexRouteImport } from './routes/brands/correas/index'
import { Route as BrandsBarbashatsIndexRouteImport } from './routes/brands/barbashats/index'
import { Route as BrandsBapeIndexRouteImport } from './routes/brands/bape/index'
import { Route as BrandsBalenciagaIndexRouteImport } from './routes/brands/balenciaga/index'
import { Route as BrandsAsicsIndexRouteImport } from './routes/brands/asics/index'
import { Route as BrandsAntiSocialClubIndexRouteImport } from './routes/brands/anti-social-club/index'
import { Route as BrandsAmiriIndexRouteImport } from './routes/brands/amiri/index'
import { Route as BrandsAlexanderMcqueenIndexRouteImport } from './routes/brands/alexander-mcqueen/index'
import { Route as Brands31HatsIndexRouteImport } from './routes/brands/31-hats/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiR2ImageSplatRouteImport } from './routes/api.r2-image.$'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin/products/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2UploadRoute = ApiR2UploadRouteImport.update({
  id: '/api/r2-upload',
  path: '/api/r2-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2ListImagesRoute = ApiR2ListImagesRouteImport.update({
  id: '/api/r2-list-images',
  path: '/api/r2-list-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2ImageRoute = ApiR2ImageRouteImport.update({
  id: '/api/r2-image',
  path: '/api/r2-image',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsVersaceIndexRoute = BrandsVersaceIndexRouteImport.update({
  id: '/brands/versace/',
  path: '/brands/versace/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsToryBurchIndexRoute = BrandsToryBurchIndexRouteImport.update({
  id: '/brands/tory-burch/',
  path: '/brands/tory-burch/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoughplayIndexRoute = BrandsRoughplayIndexRouteImport.update({
  id: '/brands/roughplay/',
  path: '/brands/roughplay/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsPradaIndexRoute = BrandsPradaIndexRouteImport.update({
  id: '/brands/prada/',
  path: '/brands/prada/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsPantallasIndexRoute = BrandsPantallasIndexRouteImport.update({
  id: '/brands/pantallas/',
  path: '/brands/pantallas/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsNikeIndexRoute = BrandsNikeIndexRouteImport.update({
  id: '/brands/nike/',
  path: '/brands/nike/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsNewBalanceIndexRoute = BrandsNewBalanceIndexRouteImport.update({
  id: '/brands/new-balance/',
  path: '/brands/new-balance/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsMixedEmotionsIndexRoute =
  BrandsMixedEmotionsIndexRouteImport.update({
    id: '/brands/mixed-emotions/',
    path: '/brands/mixed-emotions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrandsMediasIndexRoute = BrandsMediasIndexRouteImport.update({
  id: '/brands/medias/',
  path: '/brands/medias/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsLouisVuittonIndexRoute = BrandsLouisVuittonIndexRouteImport.update({
  id: '/brands/louis-vuitton/',
  path: '/brands/louis-vuitton/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsLifeHustlersIndexRoute = BrandsLifeHustlersIndexRouteImport.update({
  id: '/brands/life-hustlers/',
  path: '/brands/life-hustlers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsJordanIndexRoute = BrandsJordanIndexRouteImport.update({
  id: '/brands/jordan/',
  path: '/brands/jordan/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsJordanGorrasIndexRoute = BrandsJordanGorrasIndexRouteImport.update({
  id: '/brands/jordan-gorras/',
  path: '/brands/jordan-gorras/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsHermesParisIndexRoute = BrandsHermesParisIndexRouteImport.update({
  id: '/brands/hermes-paris/',
  path: '/brands/hermes-paris/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsHellstarIndexRoute = BrandsHellstarIndexRouteImport.update({
  id: '/brands/hellstar/',
  path: '/brands/hellstar/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsGucciIndexRoute = BrandsGucciIndexRouteImport.update({
  id: '/brands/gucci/',
  path: '/brands/gucci/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsGodspeedIndexRoute = BrandsGodspeedIndexRouteImport.update({
  id: '/brands/godspeed/',
  path: '/brands/godspeed/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsGivenchyIndexRoute = BrandsGivenchyIndexRouteImport.update({
  id: '/brands/givenchy/',
  path: '/brands/givenchy/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsGalleryDeptIndexRoute = BrandsGalleryDeptIndexRouteImport.update({
  id: '/brands/gallery-dept/',
  path: '/brands/gallery-dept/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsFendiIndexRoute = BrandsFendiIndexRouteImport.update({
  id: '/brands/fendi/',
  path: '/brands/fendi/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsEssentialsIndexRoute = BrandsEssentialsIndexRouteImport.update({
  id: '/brands/essentials/',
  path: '/brands/essentials/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsDolceGabanaIndexRoute = BrandsDolceGabanaIndexRouteImport.update({
  id: '/brands/dolce-gabana/',
  path: '/brands/dolce-gabana/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsDiorIndexRoute = BrandsDiorIndexRouteImport.update({
  id: '/brands/dior/',
  path: '/brands/dior/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsDandihatsIndexRoute = BrandsDandihatsIndexRouteImport.update({
  id: '/brands/dandihats/',
  path: '/brands/dandihats/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsCorreasIndexRoute = BrandsCorreasIndexRouteImport.update({
  id: '/brands/correas/',
  path: '/brands/correas/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBarbashatsIndexRoute = BrandsBarbashatsIndexRouteImport.update({
  id: '/brands/barbashats/',
  path: '/brands/barbashats/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBapeIndexRoute = BrandsBapeIndexRouteImport.update({
  id: '/brands/bape/',
  path: '/brands/bape/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBalenciagaIndexRoute = BrandsBalenciagaIndexRouteImport.update({
  id: '/brands/balenciaga/',
  path: '/brands/balenciaga/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsAsicsIndexRoute = BrandsAsicsIndexRouteImport.update({
  id: '/brands/asics/',
  path: '/brands/asics/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsAntiSocialClubIndexRoute =
  BrandsAntiSocialClubIndexRouteImport.update({
    id: '/brands/anti-social-club/',
    path: '/brands/anti-social-club/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrandsAmiriIndexRoute = BrandsAmiriIndexRouteImport.update({
  id: '/brands/amiri/',
  path: '/brands/amiri/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsAlexanderMcqueenIndexRoute =
  BrandsAlexanderMcqueenIndexRouteImport.update({
    id: '/brands/alexander-mcqueen/',
    path: '/brands/alexander-mcqueen/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Brands31HatsIndexRoute = Brands31HatsIndexRouteImport.update({
  id: '/brands/31-hats/',
  path: '/brands/31-hats/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2ImageSplatRoute = ApiR2ImageSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiR2ImageRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/admin/products/new',
  path: '/admin/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/admin/products/$productId',
  path: '/admin/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/r2-image': typeof ApiR2ImageRouteWithChildren
  '/api/r2-list-images': typeof ApiR2ListImagesRoute
  '/api/r2-upload': typeof ApiR2UploadRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/r2-image/$': typeof ApiR2ImageSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/brands/31-hats': typeof Brands31HatsIndexRoute
  '/brands/alexander-mcqueen': typeof BrandsAlexanderMcqueenIndexRoute
  '/brands/amiri': typeof BrandsAmiriIndexRoute
  '/brands/anti-social-club': typeof BrandsAntiSocialClubIndexRoute
  '/brands/asics': typeof BrandsAsicsIndexRoute
  '/brands/balenciaga': typeof BrandsBalenciagaIndexRoute
  '/brands/bape': typeof BrandsBapeIndexRoute
  '/brands/barbashats': typeof BrandsBarbashatsIndexRoute
  '/brands/correas': typeof BrandsCorreasIndexRoute
  '/brands/dandihats': typeof BrandsDandihatsIndexRoute
  '/brands/dior': typeof BrandsDiorIndexRoute
  '/brands/dolce-gabana': typeof BrandsDolceGabanaIndexRoute
  '/brands/essentials': typeof BrandsEssentialsIndexRoute
  '/brands/fendi': typeof BrandsFendiIndexRoute
  '/brands/gallery-dept': typeof BrandsGalleryDeptIndexRoute
  '/brands/givenchy': typeof BrandsGivenchyIndexRoute
  '/brands/godspeed': typeof BrandsGodspeedIndexRoute
  '/brands/gucci': typeof BrandsGucciIndexRoute
  '/brands/hellstar': typeof BrandsHellstarIndexRoute
  '/brands/hermes-paris': typeof BrandsHermesParisIndexRoute
  '/brands/jordan-gorras': typeof BrandsJordanGorrasIndexRoute
  '/brands/jordan': typeof BrandsJordanIndexRoute
  '/brands/life-hustlers': typeof BrandsLifeHustlersIndexRoute
  '/brands/louis-vuitton': typeof BrandsLouisVuittonIndexRoute
  '/brands/medias': typeof BrandsMediasIndexRoute
  '/brands/mixed-emotions': typeof BrandsMixedEmotionsIndexRoute
  '/brands/new-balance': typeof BrandsNewBalanceIndexRoute
  '/brands/nike': typeof BrandsNikeIndexRoute
  '/brands/pantallas': typeof BrandsPantallasIndexRoute
  '/brands/prada': typeof BrandsPradaIndexRoute
  '/brands/roughplay': typeof BrandsRoughplayIndexRoute
  '/brands/tory-burch': typeof BrandsToryBurchIndexRoute
  '/brands/versace': typeof BrandsVersaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/r2-image': typeof ApiR2ImageRouteWithChildren
  '/api/r2-list-images': typeof ApiR2ListImagesRoute
  '/api/r2-upload': typeof ApiR2UploadRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/r2-image/$': typeof ApiR2ImageSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/brands/31-hats': typeof Brands31HatsIndexRoute
  '/brands/alexander-mcqueen': typeof BrandsAlexanderMcqueenIndexRoute
  '/brands/amiri': typeof BrandsAmiriIndexRoute
  '/brands/anti-social-club': typeof BrandsAntiSocialClubIndexRoute
  '/brands/asics': typeof BrandsAsicsIndexRoute
  '/brands/balenciaga': typeof BrandsBalenciagaIndexRoute
  '/brands/bape': typeof BrandsBapeIndexRoute
  '/brands/barbashats': typeof BrandsBarbashatsIndexRoute
  '/brands/correas': typeof BrandsCorreasIndexRoute
  '/brands/dandihats': typeof BrandsDandihatsIndexRoute
  '/brands/dior': typeof BrandsDiorIndexRoute
  '/brands/dolce-gabana': typeof BrandsDolceGabanaIndexRoute
  '/brands/essentials': typeof BrandsEssentialsIndexRoute
  '/brands/fendi': typeof BrandsFendiIndexRoute
  '/brands/gallery-dept': typeof BrandsGalleryDeptIndexRoute
  '/brands/givenchy': typeof BrandsGivenchyIndexRoute
  '/brands/godspeed': typeof BrandsGodspeedIndexRoute
  '/brands/gucci': typeof BrandsGucciIndexRoute
  '/brands/hellstar': typeof BrandsHellstarIndexRoute
  '/brands/hermes-paris': typeof BrandsHermesParisIndexRoute
  '/brands/jordan-gorras': typeof BrandsJordanGorrasIndexRoute
  '/brands/jordan': typeof BrandsJordanIndexRoute
  '/brands/life-hustlers': typeof BrandsLifeHustlersIndexRoute
  '/brands/louis-vuitton': typeof BrandsLouisVuittonIndexRoute
  '/brands/medias': typeof BrandsMediasIndexRoute
  '/brands/mixed-emotions': typeof BrandsMixedEmotionsIndexRoute
  '/brands/new-balance': typeof BrandsNewBalanceIndexRoute
  '/brands/nike': typeof BrandsNikeIndexRoute
  '/brands/pantallas': typeof BrandsPantallasIndexRoute
  '/brands/prada': typeof BrandsPradaIndexRoute
  '/brands/roughplay': typeof BrandsRoughplayIndexRoute
  '/brands/tory-burch': typeof BrandsToryBurchIndexRoute
  '/brands/versace': typeof BrandsVersaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/r2-image': typeof ApiR2ImageRouteWithChildren
  '/api/r2-list-images': typeof ApiR2ListImagesRoute
  '/api/r2-upload': typeof ApiR2UploadRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/r2-image/$': typeof ApiR2ImageSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/brands/31-hats/': typeof Brands31HatsIndexRoute
  '/brands/alexander-mcqueen/': typeof BrandsAlexanderMcqueenIndexRoute
  '/brands/amiri/': typeof BrandsAmiriIndexRoute
  '/brands/anti-social-club/': typeof BrandsAntiSocialClubIndexRoute
  '/brands/asics/': typeof BrandsAsicsIndexRoute
  '/brands/balenciaga/': typeof BrandsBalenciagaIndexRoute
  '/brands/bape/': typeof BrandsBapeIndexRoute
  '/brands/barbashats/': typeof BrandsBarbashatsIndexRoute
  '/brands/correas/': typeof BrandsCorreasIndexRoute
  '/brands/dandihats/': typeof BrandsDandihatsIndexRoute
  '/brands/dior/': typeof BrandsDiorIndexRoute
  '/brands/dolce-gabana/': typeof BrandsDolceGabanaIndexRoute
  '/brands/essentials/': typeof BrandsEssentialsIndexRoute
  '/brands/fendi/': typeof BrandsFendiIndexRoute
  '/brands/gallery-dept/': typeof BrandsGalleryDeptIndexRoute
  '/brands/givenchy/': typeof BrandsGivenchyIndexRoute
  '/brands/godspeed/': typeof BrandsGodspeedIndexRoute
  '/brands/gucci/': typeof BrandsGucciIndexRoute
  '/brands/hellstar/': typeof BrandsHellstarIndexRoute
  '/brands/hermes-paris/': typeof BrandsHermesParisIndexRoute
  '/brands/jordan-gorras/': typeof BrandsJordanGorrasIndexRoute
  '/brands/jordan/': typeof BrandsJordanIndexRoute
  '/brands/life-hustlers/': typeof BrandsLifeHustlersIndexRoute
  '/brands/louis-vuitton/': typeof BrandsLouisVuittonIndexRoute
  '/brands/medias/': typeof BrandsMediasIndexRoute
  '/brands/mixed-emotions/': typeof BrandsMixedEmotionsIndexRoute
  '/brands/new-balance/': typeof BrandsNewBalanceIndexRoute
  '/brands/nike/': typeof BrandsNikeIndexRoute
  '/brands/pantallas/': typeof BrandsPantallasIndexRoute
  '/brands/prada/': typeof BrandsPradaIndexRoute
  '/brands/roughplay/': typeof BrandsRoughplayIndexRoute
  '/brands/tory-burch/': typeof BrandsToryBurchIndexRoute
  '/brands/versace/': typeof BrandsVersaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/r2-image'
    | '/api/r2-list-images'
    | '/api/r2-upload'
    | '/product/$productId'
    | '/admin'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/api/r2-image/$'
    | '/api/trpc/$'
    | '/admin/products'
    | '/brands/31-hats'
    | '/brands/alexander-mcqueen'
    | '/brands/amiri'
    | '/brands/anti-social-club'
    | '/brands/asics'
    | '/brands/balenciaga'
    | '/brands/bape'
    | '/brands/barbashats'
    | '/brands/correas'
    | '/brands/dandihats'
    | '/brands/dior'
    | '/brands/dolce-gabana'
    | '/brands/essentials'
    | '/brands/fendi'
    | '/brands/gallery-dept'
    | '/brands/givenchy'
    | '/brands/godspeed'
    | '/brands/gucci'
    | '/brands/hellstar'
    | '/brands/hermes-paris'
    | '/brands/jordan-gorras'
    | '/brands/jordan'
    | '/brands/life-hustlers'
    | '/brands/louis-vuitton'
    | '/brands/medias'
    | '/brands/mixed-emotions'
    | '/brands/new-balance'
    | '/brands/nike'
    | '/brands/pantallas'
    | '/brands/prada'
    | '/brands/roughplay'
    | '/brands/tory-burch'
    | '/brands/versace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/r2-image'
    | '/api/r2-list-images'
    | '/api/r2-upload'
    | '/product/$productId'
    | '/admin'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/api/r2-image/$'
    | '/api/trpc/$'
    | '/admin/products'
    | '/brands/31-hats'
    | '/brands/alexander-mcqueen'
    | '/brands/amiri'
    | '/brands/anti-social-club'
    | '/brands/asics'
    | '/brands/balenciaga'
    | '/brands/bape'
    | '/brands/barbashats'
    | '/brands/correas'
    | '/brands/dandihats'
    | '/brands/dior'
    | '/brands/dolce-gabana'
    | '/brands/essentials'
    | '/brands/fendi'
    | '/brands/gallery-dept'
    | '/brands/givenchy'
    | '/brands/godspeed'
    | '/brands/gucci'
    | '/brands/hellstar'
    | '/brands/hermes-paris'
    | '/brands/jordan-gorras'
    | '/brands/jordan'
    | '/brands/life-hustlers'
    | '/brands/louis-vuitton'
    | '/brands/medias'
    | '/brands/mixed-emotions'
    | '/brands/new-balance'
    | '/brands/nike'
    | '/brands/pantallas'
    | '/brands/prada'
    | '/brands/roughplay'
    | '/brands/tory-burch'
    | '/brands/versace'
  id:
    | '__root__'
    | '/'
    | '/api/r2-image'
    | '/api/r2-list-images'
    | '/api/r2-upload'
    | '/product/$productId'
    | '/admin/'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/api/r2-image/$'
    | '/api/trpc/$'
    | '/admin/products/'
    | '/brands/31-hats/'
    | '/brands/alexander-mcqueen/'
    | '/brands/amiri/'
    | '/brands/anti-social-club/'
    | '/brands/asics/'
    | '/brands/balenciaga/'
    | '/brands/bape/'
    | '/brands/barbashats/'
    | '/brands/correas/'
    | '/brands/dandihats/'
    | '/brands/dior/'
    | '/brands/dolce-gabana/'
    | '/brands/essentials/'
    | '/brands/fendi/'
    | '/brands/gallery-dept/'
    | '/brands/givenchy/'
    | '/brands/godspeed/'
    | '/brands/gucci/'
    | '/brands/hellstar/'
    | '/brands/hermes-paris/'
    | '/brands/jordan-gorras/'
    | '/brands/jordan/'
    | '/brands/life-hustlers/'
    | '/brands/louis-vuitton/'
    | '/brands/medias/'
    | '/brands/mixed-emotions/'
    | '/brands/new-balance/'
    | '/brands/nike/'
    | '/brands/pantallas/'
    | '/brands/prada/'
    | '/brands/roughplay/'
    | '/brands/tory-burch/'
    | '/brands/versace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiR2ImageRoute: typeof ApiR2ImageRouteWithChildren
  ApiR2ListImagesRoute: typeof ApiR2ListImagesRoute
  ApiR2UploadRoute: typeof ApiR2UploadRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  Brands31HatsIndexRoute: typeof Brands31HatsIndexRoute
  BrandsAlexanderMcqueenIndexRoute: typeof BrandsAlexanderMcqueenIndexRoute
  BrandsAmiriIndexRoute: typeof BrandsAmiriIndexRoute
  BrandsAntiSocialClubIndexRoute: typeof BrandsAntiSocialClubIndexRoute
  BrandsAsicsIndexRoute: typeof BrandsAsicsIndexRoute
  BrandsBalenciagaIndexRoute: typeof BrandsBalenciagaIndexRoute
  BrandsBapeIndexRoute: typeof BrandsBapeIndexRoute
  BrandsBarbashatsIndexRoute: typeof BrandsBarbashatsIndexRoute
  BrandsCorreasIndexRoute: typeof BrandsCorreasIndexRoute
  BrandsDandihatsIndexRoute: typeof BrandsDandihatsIndexRoute
  BrandsDiorIndexRoute: typeof BrandsDiorIndexRoute
  BrandsDolceGabanaIndexRoute: typeof BrandsDolceGabanaIndexRoute
  BrandsEssentialsIndexRoute: typeof BrandsEssentialsIndexRoute
  BrandsFendiIndexRoute: typeof BrandsFendiIndexRoute
  BrandsGalleryDeptIndexRoute: typeof BrandsGalleryDeptIndexRoute
  BrandsGivenchyIndexRoute: typeof BrandsGivenchyIndexRoute
  BrandsGodspeedIndexRoute: typeof BrandsGodspeedIndexRoute
  BrandsGucciIndexRoute: typeof BrandsGucciIndexRoute
  BrandsHellstarIndexRoute: typeof BrandsHellstarIndexRoute
  BrandsHermesParisIndexRoute: typeof BrandsHermesParisIndexRoute
  BrandsJordanGorrasIndexRoute: typeof BrandsJordanGorrasIndexRoute
  BrandsJordanIndexRoute: typeof BrandsJordanIndexRoute
  BrandsLifeHustlersIndexRoute: typeof BrandsLifeHustlersIndexRoute
  BrandsLouisVuittonIndexRoute: typeof BrandsLouisVuittonIndexRoute
  BrandsMediasIndexRoute: typeof BrandsMediasIndexRoute
  BrandsMixedEmotionsIndexRoute: typeof BrandsMixedEmotionsIndexRoute
  BrandsNewBalanceIndexRoute: typeof BrandsNewBalanceIndexRoute
  BrandsNikeIndexRoute: typeof BrandsNikeIndexRoute
  BrandsPantallasIndexRoute: typeof BrandsPantallasIndexRoute
  BrandsPradaIndexRoute: typeof BrandsPradaIndexRoute
  BrandsRoughplayIndexRoute: typeof BrandsRoughplayIndexRoute
  BrandsToryBurchIndexRoute: typeof BrandsToryBurchIndexRoute
  BrandsVersaceIndexRoute: typeof BrandsVersaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2-upload': {
      id: '/api/r2-upload'
      path: '/api/r2-upload'
      fullPath: '/api/r2-upload'
      preLoaderRoute: typeof ApiR2UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2-list-images': {
      id: '/api/r2-list-images'
      path: '/api/r2-list-images'
      fullPath: '/api/r2-list-images'
      preLoaderRoute: typeof ApiR2ListImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2-image': {
      id: '/api/r2-image'
      path: '/api/r2-image'
      fullPath: '/api/r2-image'
      preLoaderRoute: typeof ApiR2ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/versace/': {
      id: '/brands/versace/'
      path: '/brands/versace'
      fullPath: '/brands/versace'
      preLoaderRoute: typeof BrandsVersaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/tory-burch/': {
      id: '/brands/tory-burch/'
      path: '/brands/tory-burch'
      fullPath: '/brands/tory-burch'
      preLoaderRoute: typeof BrandsToryBurchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/roughplay/': {
      id: '/brands/roughplay/'
      path: '/brands/roughplay'
      fullPath: '/brands/roughplay'
      preLoaderRoute: typeof BrandsRoughplayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/prada/': {
      id: '/brands/prada/'
      path: '/brands/prada'
      fullPath: '/brands/prada'
      preLoaderRoute: typeof BrandsPradaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/pantallas/': {
      id: '/brands/pantallas/'
      path: '/brands/pantallas'
      fullPath: '/brands/pantallas'
      preLoaderRoute: typeof BrandsPantallasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/nike/': {
      id: '/brands/nike/'
      path: '/brands/nike'
      fullPath: '/brands/nike'
      preLoaderRoute: typeof BrandsNikeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/new-balance/': {
      id: '/brands/new-balance/'
      path: '/brands/new-balance'
      fullPath: '/brands/new-balance'
      preLoaderRoute: typeof BrandsNewBalanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/mixed-emotions/': {
      id: '/brands/mixed-emotions/'
      path: '/brands/mixed-emotions'
      fullPath: '/brands/mixed-emotions'
      preLoaderRoute: typeof BrandsMixedEmotionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/medias/': {
      id: '/brands/medias/'
      path: '/brands/medias'
      fullPath: '/brands/medias'
      preLoaderRoute: typeof BrandsMediasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/louis-vuitton/': {
      id: '/brands/louis-vuitton/'
      path: '/brands/louis-vuitton'
      fullPath: '/brands/louis-vuitton'
      preLoaderRoute: typeof BrandsLouisVuittonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/life-hustlers/': {
      id: '/brands/life-hustlers/'
      path: '/brands/life-hustlers'
      fullPath: '/brands/life-hustlers'
      preLoaderRoute: typeof BrandsLifeHustlersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/jordan/': {
      id: '/brands/jordan/'
      path: '/brands/jordan'
      fullPath: '/brands/jordan'
      preLoaderRoute: typeof BrandsJordanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/jordan-gorras/': {
      id: '/brands/jordan-gorras/'
      path: '/brands/jordan-gorras'
      fullPath: '/brands/jordan-gorras'
      preLoaderRoute: typeof BrandsJordanGorrasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/hermes-paris/': {
      id: '/brands/hermes-paris/'
      path: '/brands/hermes-paris'
      fullPath: '/brands/hermes-paris'
      preLoaderRoute: typeof BrandsHermesParisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/hellstar/': {
      id: '/brands/hellstar/'
      path: '/brands/hellstar'
      fullPath: '/brands/hellstar'
      preLoaderRoute: typeof BrandsHellstarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/gucci/': {
      id: '/brands/gucci/'
      path: '/brands/gucci'
      fullPath: '/brands/gucci'
      preLoaderRoute: typeof BrandsGucciIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/godspeed/': {
      id: '/brands/godspeed/'
      path: '/brands/godspeed'
      fullPath: '/brands/godspeed'
      preLoaderRoute: typeof BrandsGodspeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/givenchy/': {
      id: '/brands/givenchy/'
      path: '/brands/givenchy'
      fullPath: '/brands/givenchy'
      preLoaderRoute: typeof BrandsGivenchyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/gallery-dept/': {
      id: '/brands/gallery-dept/'
      path: '/brands/gallery-dept'
      fullPath: '/brands/gallery-dept'
      preLoaderRoute: typeof BrandsGalleryDeptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/fendi/': {
      id: '/brands/fendi/'
      path: '/brands/fendi'
      fullPath: '/brands/fendi'
      preLoaderRoute: typeof BrandsFendiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/essentials/': {
      id: '/brands/essentials/'
      path: '/brands/essentials'
      fullPath: '/brands/essentials'
      preLoaderRoute: typeof BrandsEssentialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/dolce-gabana/': {
      id: '/brands/dolce-gabana/'
      path: '/brands/dolce-gabana'
      fullPath: '/brands/dolce-gabana'
      preLoaderRoute: typeof BrandsDolceGabanaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/dior/': {
      id: '/brands/dior/'
      path: '/brands/dior'
      fullPath: '/brands/dior'
      preLoaderRoute: typeof BrandsDiorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/dandihats/': {
      id: '/brands/dandihats/'
      path: '/brands/dandihats'
      fullPath: '/brands/dandihats'
      preLoaderRoute: typeof BrandsDandihatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/correas/': {
      id: '/brands/correas/'
      path: '/brands/correas'
      fullPath: '/brands/correas'
      preLoaderRoute: typeof BrandsCorreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/barbashats/': {
      id: '/brands/barbashats/'
      path: '/brands/barbashats'
      fullPath: '/brands/barbashats'
      preLoaderRoute: typeof BrandsBarbashatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/bape/': {
      id: '/brands/bape/'
      path: '/brands/bape'
      fullPath: '/brands/bape'
      preLoaderRoute: typeof BrandsBapeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/balenciaga/': {
      id: '/brands/balenciaga/'
      path: '/brands/balenciaga'
      fullPath: '/brands/balenciaga'
      preLoaderRoute: typeof BrandsBalenciagaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/asics/': {
      id: '/brands/asics/'
      path: '/brands/asics'
      fullPath: '/brands/asics'
      preLoaderRoute: typeof BrandsAsicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/anti-social-club/': {
      id: '/brands/anti-social-club/'
      path: '/brands/anti-social-club'
      fullPath: '/brands/anti-social-club'
      preLoaderRoute: typeof BrandsAntiSocialClubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/amiri/': {
      id: '/brands/amiri/'
      path: '/brands/amiri'
      fullPath: '/brands/amiri'
      preLoaderRoute: typeof BrandsAmiriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/alexander-mcqueen/': {
      id: '/brands/alexander-mcqueen/'
      path: '/brands/alexander-mcqueen'
      fullPath: '/brands/alexander-mcqueen'
      preLoaderRoute: typeof BrandsAlexanderMcqueenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/31-hats/': {
      id: '/brands/31-hats/'
      path: '/brands/31-hats'
      fullPath: '/brands/31-hats'
      preLoaderRoute: typeof Brands31HatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2-image/$': {
      id: '/api/r2-image/$'
      path: '/$'
      fullPath: '/api/r2-image/$'
      preLoaderRoute: typeof ApiR2ImageSplatRouteImport
      parentRoute: typeof ApiR2ImageRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$productId': {
      id: '/admin/products/$productId'
      path: '/admin/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiR2ImageRouteChildren {
  ApiR2ImageSplatRoute: typeof ApiR2ImageSplatRoute
}

const ApiR2ImageRouteChildren: ApiR2ImageRouteChildren = {
  ApiR2ImageSplatRoute: ApiR2ImageSplatRoute,
}

const ApiR2ImageRouteWithChildren = ApiR2ImageRoute._addFileChildren(
  ApiR2ImageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiR2ImageRoute: ApiR2ImageRouteWithChildren,
  ApiR2ListImagesRoute: ApiR2ListImagesRoute,
  ApiR2UploadRoute: ApiR2UploadRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  Brands31HatsIndexRoute: Brands31HatsIndexRoute,
  BrandsAlexanderMcqueenIndexRoute: BrandsAlexanderMcqueenIndexRoute,
  BrandsAmiriIndexRoute: BrandsAmiriIndexRoute,
  BrandsAntiSocialClubIndexRoute: BrandsAntiSocialClubIndexRoute,
  BrandsAsicsIndexRoute: BrandsAsicsIndexRoute,
  BrandsBalenciagaIndexRoute: BrandsBalenciagaIndexRoute,
  BrandsBapeIndexRoute: BrandsBapeIndexRoute,
  BrandsBarbashatsIndexRoute: BrandsBarbashatsIndexRoute,
  BrandsCorreasIndexRoute: BrandsCorreasIndexRoute,
  BrandsDandihatsIndexRoute: BrandsDandihatsIndexRoute,
  BrandsDiorIndexRoute: BrandsDiorIndexRoute,
  BrandsDolceGabanaIndexRoute: BrandsDolceGabanaIndexRoute,
  BrandsEssentialsIndexRoute: BrandsEssentialsIndexRoute,
  BrandsFendiIndexRoute: BrandsFendiIndexRoute,
  BrandsGalleryDeptIndexRoute: BrandsGalleryDeptIndexRoute,
  BrandsGivenchyIndexRoute: BrandsGivenchyIndexRoute,
  BrandsGodspeedIndexRoute: BrandsGodspeedIndexRoute,
  BrandsGucciIndexRoute: BrandsGucciIndexRoute,
  BrandsHellstarIndexRoute: BrandsHellstarIndexRoute,
  BrandsHermesParisIndexRoute: BrandsHermesParisIndexRoute,
  BrandsJordanGorrasIndexRoute: BrandsJordanGorrasIndexRoute,
  BrandsJordanIndexRoute: BrandsJordanIndexRoute,
  BrandsLifeHustlersIndexRoute: BrandsLifeHustlersIndexRoute,
  BrandsLouisVuittonIndexRoute: BrandsLouisVuittonIndexRoute,
  BrandsMediasIndexRoute: BrandsMediasIndexRoute,
  BrandsMixedEmotionsIndexRoute: BrandsMixedEmotionsIndexRoute,
  BrandsNewBalanceIndexRoute: BrandsNewBalanceIndexRoute,
  BrandsNikeIndexRoute: BrandsNikeIndexRoute,
  BrandsPantallasIndexRoute: BrandsPantallasIndexRoute,
  BrandsPradaIndexRoute: BrandsPradaIndexRoute,
  BrandsRoughplayIndexRoute: BrandsRoughplayIndexRoute,
  BrandsToryBurchIndexRoute: BrandsToryBurchIndexRoute,
  BrandsVersaceIndexRoute: BrandsVersaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
