/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiR2UploadRouteImport } from './routes/api.r2-upload'
import { Route as ApiR2ListImagesRouteImport } from './routes/api.r2-list-images'
import { Route as ApiR2ImageRouteImport } from './routes/api.r2-image'
import { Route as BrandsPradaIndexRouteImport } from './routes/brands/prada/index'
import { Route as BrandsNikeIndexRouteImport } from './routes/brands/nike/index'
import { Route as BrandsNewBalanceIndexRouteImport } from './routes/brands/new-balance/index'
import { Route as BrandsLouisVuittonIndexRouteImport } from './routes/brands/louis-vuitton/index'
import { Route as BrandsJordanIndexRouteImport } from './routes/brands/jordan/index'
import { Route as BrandsGucciIndexRouteImport } from './routes/brands/gucci/index'
import { Route as BrandsDolceGabanaIndexRouteImport } from './routes/brands/dolce-gabana/index'
import { Route as BrandsDiorIndexRouteImport } from './routes/brands/dior/index'
import { Route as BrandsBapeIndexRouteImport } from './routes/brands/bape/index'
import { Route as BrandsBalenciagaIndexRouteImport } from './routes/brands/balenciaga/index'
import { Route as BrandsAsicsIndexRouteImport } from './routes/brands/asics/index'
import { Route as BrandsAmiriIndexRouteImport } from './routes/brands/amiri/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiR2ImageSplatRouteImport } from './routes/api.r2-image.$'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin/products/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2UploadRoute = ApiR2UploadRouteImport.update({
  id: '/api/r2-upload',
  path: '/api/r2-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2ListImagesRoute = ApiR2ListImagesRouteImport.update({
  id: '/api/r2-list-images',
  path: '/api/r2-list-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2ImageRoute = ApiR2ImageRouteImport.update({
  id: '/api/r2-image',
  path: '/api/r2-image',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsPradaIndexRoute = BrandsPradaIndexRouteImport.update({
  id: '/brands/prada/',
  path: '/brands/prada/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsNikeIndexRoute = BrandsNikeIndexRouteImport.update({
  id: '/brands/nike/',
  path: '/brands/nike/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsNewBalanceIndexRoute = BrandsNewBalanceIndexRouteImport.update({
  id: '/brands/new-balance/',
  path: '/brands/new-balance/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsLouisVuittonIndexRoute = BrandsLouisVuittonIndexRouteImport.update({
  id: '/brands/louis-vuitton/',
  path: '/brands/louis-vuitton/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsJordanIndexRoute = BrandsJordanIndexRouteImport.update({
  id: '/brands/jordan/',
  path: '/brands/jordan/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsGucciIndexRoute = BrandsGucciIndexRouteImport.update({
  id: '/brands/gucci/',
  path: '/brands/gucci/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsDolceGabanaIndexRoute = BrandsDolceGabanaIndexRouteImport.update({
  id: '/brands/dolce-gabana/',
  path: '/brands/dolce-gabana/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsDiorIndexRoute = BrandsDiorIndexRouteImport.update({
  id: '/brands/dior/',
  path: '/brands/dior/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBapeIndexRoute = BrandsBapeIndexRouteImport.update({
  id: '/brands/bape/',
  path: '/brands/bape/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBalenciagaIndexRoute = BrandsBalenciagaIndexRouteImport.update({
  id: '/brands/balenciaga/',
  path: '/brands/balenciaga/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsAsicsIndexRoute = BrandsAsicsIndexRouteImport.update({
  id: '/brands/asics/',
  path: '/brands/asics/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsAmiriIndexRoute = BrandsAmiriIndexRouteImport.update({
  id: '/brands/amiri/',
  path: '/brands/amiri/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2ImageSplatRoute = ApiR2ImageSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiR2ImageRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/admin/products/new',
  path: '/admin/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/admin/products/$productId',
  path: '/admin/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/r2-image': typeof ApiR2ImageRouteWithChildren
  '/api/r2-list-images': typeof ApiR2ListImagesRoute
  '/api/r2-upload': typeof ApiR2UploadRoute
  '/admin': typeof AdminIndexRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/r2-image/$': typeof ApiR2ImageSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/brands/amiri': typeof BrandsAmiriIndexRoute
  '/brands/asics': typeof BrandsAsicsIndexRoute
  '/brands/balenciaga': typeof BrandsBalenciagaIndexRoute
  '/brands/bape': typeof BrandsBapeIndexRoute
  '/brands/dior': typeof BrandsDiorIndexRoute
  '/brands/dolce-gabana': typeof BrandsDolceGabanaIndexRoute
  '/brands/gucci': typeof BrandsGucciIndexRoute
  '/brands/jordan': typeof BrandsJordanIndexRoute
  '/brands/louis-vuitton': typeof BrandsLouisVuittonIndexRoute
  '/brands/new-balance': typeof BrandsNewBalanceIndexRoute
  '/brands/nike': typeof BrandsNikeIndexRoute
  '/brands/prada': typeof BrandsPradaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/r2-image': typeof ApiR2ImageRouteWithChildren
  '/api/r2-list-images': typeof ApiR2ListImagesRoute
  '/api/r2-upload': typeof ApiR2UploadRoute
  '/admin': typeof AdminIndexRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/r2-image/$': typeof ApiR2ImageSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/brands/amiri': typeof BrandsAmiriIndexRoute
  '/brands/asics': typeof BrandsAsicsIndexRoute
  '/brands/balenciaga': typeof BrandsBalenciagaIndexRoute
  '/brands/bape': typeof BrandsBapeIndexRoute
  '/brands/dior': typeof BrandsDiorIndexRoute
  '/brands/dolce-gabana': typeof BrandsDolceGabanaIndexRoute
  '/brands/gucci': typeof BrandsGucciIndexRoute
  '/brands/jordan': typeof BrandsJordanIndexRoute
  '/brands/louis-vuitton': typeof BrandsLouisVuittonIndexRoute
  '/brands/new-balance': typeof BrandsNewBalanceIndexRoute
  '/brands/nike': typeof BrandsNikeIndexRoute
  '/brands/prada': typeof BrandsPradaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/r2-image': typeof ApiR2ImageRouteWithChildren
  '/api/r2-list-images': typeof ApiR2ListImagesRoute
  '/api/r2-upload': typeof ApiR2UploadRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/r2-image/$': typeof ApiR2ImageSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/brands/amiri/': typeof BrandsAmiriIndexRoute
  '/brands/asics/': typeof BrandsAsicsIndexRoute
  '/brands/balenciaga/': typeof BrandsBalenciagaIndexRoute
  '/brands/bape/': typeof BrandsBapeIndexRoute
  '/brands/dior/': typeof BrandsDiorIndexRoute
  '/brands/dolce-gabana/': typeof BrandsDolceGabanaIndexRoute
  '/brands/gucci/': typeof BrandsGucciIndexRoute
  '/brands/jordan/': typeof BrandsJordanIndexRoute
  '/brands/louis-vuitton/': typeof BrandsLouisVuittonIndexRoute
  '/brands/new-balance/': typeof BrandsNewBalanceIndexRoute
  '/brands/nike/': typeof BrandsNikeIndexRoute
  '/brands/prada/': typeof BrandsPradaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/r2-image'
    | '/api/r2-list-images'
    | '/api/r2-upload'
    | '/admin'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/api/r2-image/$'
    | '/api/trpc/$'
    | '/admin/products'
    | '/brands/amiri'
    | '/brands/asics'
    | '/brands/balenciaga'
    | '/brands/bape'
    | '/brands/dior'
    | '/brands/dolce-gabana'
    | '/brands/gucci'
    | '/brands/jordan'
    | '/brands/louis-vuitton'
    | '/brands/new-balance'
    | '/brands/nike'
    | '/brands/prada'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/r2-image'
    | '/api/r2-list-images'
    | '/api/r2-upload'
    | '/admin'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/api/r2-image/$'
    | '/api/trpc/$'
    | '/admin/products'
    | '/brands/amiri'
    | '/brands/asics'
    | '/brands/balenciaga'
    | '/brands/bape'
    | '/brands/dior'
    | '/brands/dolce-gabana'
    | '/brands/gucci'
    | '/brands/jordan'
    | '/brands/louis-vuitton'
    | '/brands/new-balance'
    | '/brands/nike'
    | '/brands/prada'
  id:
    | '__root__'
    | '/'
    | '/api/r2-image'
    | '/api/r2-list-images'
    | '/api/r2-upload'
    | '/admin/'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/api/r2-image/$'
    | '/api/trpc/$'
    | '/admin/products/'
    | '/brands/amiri/'
    | '/brands/asics/'
    | '/brands/balenciaga/'
    | '/brands/bape/'
    | '/brands/dior/'
    | '/brands/dolce-gabana/'
    | '/brands/gucci/'
    | '/brands/jordan/'
    | '/brands/louis-vuitton/'
    | '/brands/new-balance/'
    | '/brands/nike/'
    | '/brands/prada/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiR2ImageRoute: typeof ApiR2ImageRouteWithChildren
  ApiR2ListImagesRoute: typeof ApiR2ListImagesRoute
  ApiR2UploadRoute: typeof ApiR2UploadRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  BrandsAmiriIndexRoute: typeof BrandsAmiriIndexRoute
  BrandsAsicsIndexRoute: typeof BrandsAsicsIndexRoute
  BrandsBalenciagaIndexRoute: typeof BrandsBalenciagaIndexRoute
  BrandsBapeIndexRoute: typeof BrandsBapeIndexRoute
  BrandsDiorIndexRoute: typeof BrandsDiorIndexRoute
  BrandsDolceGabanaIndexRoute: typeof BrandsDolceGabanaIndexRoute
  BrandsGucciIndexRoute: typeof BrandsGucciIndexRoute
  BrandsJordanIndexRoute: typeof BrandsJordanIndexRoute
  BrandsLouisVuittonIndexRoute: typeof BrandsLouisVuittonIndexRoute
  BrandsNewBalanceIndexRoute: typeof BrandsNewBalanceIndexRoute
  BrandsNikeIndexRoute: typeof BrandsNikeIndexRoute
  BrandsPradaIndexRoute: typeof BrandsPradaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2-upload': {
      id: '/api/r2-upload'
      path: '/api/r2-upload'
      fullPath: '/api/r2-upload'
      preLoaderRoute: typeof ApiR2UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2-list-images': {
      id: '/api/r2-list-images'
      path: '/api/r2-list-images'
      fullPath: '/api/r2-list-images'
      preLoaderRoute: typeof ApiR2ListImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2-image': {
      id: '/api/r2-image'
      path: '/api/r2-image'
      fullPath: '/api/r2-image'
      preLoaderRoute: typeof ApiR2ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/prada/': {
      id: '/brands/prada/'
      path: '/brands/prada'
      fullPath: '/brands/prada'
      preLoaderRoute: typeof BrandsPradaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/nike/': {
      id: '/brands/nike/'
      path: '/brands/nike'
      fullPath: '/brands/nike'
      preLoaderRoute: typeof BrandsNikeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/new-balance/': {
      id: '/brands/new-balance/'
      path: '/brands/new-balance'
      fullPath: '/brands/new-balance'
      preLoaderRoute: typeof BrandsNewBalanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/louis-vuitton/': {
      id: '/brands/louis-vuitton/'
      path: '/brands/louis-vuitton'
      fullPath: '/brands/louis-vuitton'
      preLoaderRoute: typeof BrandsLouisVuittonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/jordan/': {
      id: '/brands/jordan/'
      path: '/brands/jordan'
      fullPath: '/brands/jordan'
      preLoaderRoute: typeof BrandsJordanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/gucci/': {
      id: '/brands/gucci/'
      path: '/brands/gucci'
      fullPath: '/brands/gucci'
      preLoaderRoute: typeof BrandsGucciIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/dolce-gabana/': {
      id: '/brands/dolce-gabana/'
      path: '/brands/dolce-gabana'
      fullPath: '/brands/dolce-gabana'
      preLoaderRoute: typeof BrandsDolceGabanaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/dior/': {
      id: '/brands/dior/'
      path: '/brands/dior'
      fullPath: '/brands/dior'
      preLoaderRoute: typeof BrandsDiorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/bape/': {
      id: '/brands/bape/'
      path: '/brands/bape'
      fullPath: '/brands/bape'
      preLoaderRoute: typeof BrandsBapeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/balenciaga/': {
      id: '/brands/balenciaga/'
      path: '/brands/balenciaga'
      fullPath: '/brands/balenciaga'
      preLoaderRoute: typeof BrandsBalenciagaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/asics/': {
      id: '/brands/asics/'
      path: '/brands/asics'
      fullPath: '/brands/asics'
      preLoaderRoute: typeof BrandsAsicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/amiri/': {
      id: '/brands/amiri/'
      path: '/brands/amiri'
      fullPath: '/brands/amiri'
      preLoaderRoute: typeof BrandsAmiriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2-image/$': {
      id: '/api/r2-image/$'
      path: '/$'
      fullPath: '/api/r2-image/$'
      preLoaderRoute: typeof ApiR2ImageSplatRouteImport
      parentRoute: typeof ApiR2ImageRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$productId': {
      id: '/admin/products/$productId'
      path: '/admin/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiR2ImageRouteChildren {
  ApiR2ImageSplatRoute: typeof ApiR2ImageSplatRoute
}

const ApiR2ImageRouteChildren: ApiR2ImageRouteChildren = {
  ApiR2ImageSplatRoute: ApiR2ImageSplatRoute,
}

const ApiR2ImageRouteWithChildren = ApiR2ImageRoute._addFileChildren(
  ApiR2ImageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiR2ImageRoute: ApiR2ImageRouteWithChildren,
  ApiR2ListImagesRoute: ApiR2ListImagesRoute,
  ApiR2UploadRoute: ApiR2UploadRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  BrandsAmiriIndexRoute: BrandsAmiriIndexRoute,
  BrandsAsicsIndexRoute: BrandsAsicsIndexRoute,
  BrandsBalenciagaIndexRoute: BrandsBalenciagaIndexRoute,
  BrandsBapeIndexRoute: BrandsBapeIndexRoute,
  BrandsDiorIndexRoute: BrandsDiorIndexRoute,
  BrandsDolceGabanaIndexRoute: BrandsDolceGabanaIndexRoute,
  BrandsGucciIndexRoute: BrandsGucciIndexRoute,
  BrandsJordanIndexRoute: BrandsJordanIndexRoute,
  BrandsLouisVuittonIndexRoute: BrandsLouisVuittonIndexRoute,
  BrandsNewBalanceIndexRoute: BrandsNewBalanceIndexRoute,
  BrandsNikeIndexRoute: BrandsNikeIndexRoute,
  BrandsPradaIndexRoute: BrandsPradaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
